name: Terraform CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Validate, Format, Plan, Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Format Check (root + alle Unterordner)
      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      # Init & Validate (root module)
      - name: Terraform Init & Validate (root module)
        run: |
          terraform init
          terraform validate

      # Init & Validate (basic example)
      - name: Terraform Init & Validate (basic example)
        working-directory: examples/basic
        run: |
          terraform init
          terraform validate

      # Terraform Plan (basic example)
      - name: Terraform Plan (basic example)
        working-directory: examples/basic
        run: terraform plan -no-color

      # Checkov Security Scan (root module)
      - name: Run Checkov (root module)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: true

      # Checkov Security Scan (basic example)
      - name: Run Checkov (basic example)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: examples/basic
          quiet: true
          soft_fail: true
